---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-dp
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      volumes:
        - name: kibana-cert
          secret:
            secretName: kibana-cert
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.5.3-amd64
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "[\"https://elastic-svc:9200\"]"
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "[\"/usr/share/kibana/config/certs/ca.crt\"]"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: certificate
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: kibana_system_password
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_SSL_CERTIFICATE
              value: /usr/share/kibana/config/certs/tls.crt
            - name: SERVER_SSL_KEY
              value: /usr/share/kibana/config/certs/tls.key
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: kibana_key
          volumeMounts:
            - name: kibana-cert
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
          ports:
            - containerPort: 5601
