---

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml

secretGenerator:
  - name: kibana-elastic-cred
    type: Opaque
  - name: kibana-object-key
    type: Opaque
  - name: kibana-cert
    type: kubernetes.io/tls
